# Generated by Django 3.1.6 on 2021-09-29 09:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0007_image_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='slug',
        ),
    ]
