# Generated by Django 3.1.6 on 2021-10-01 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0008_remove_image_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='slug',
            field=models.SlugField(blank=True, max_length=200, verbose_name='اسلاگ'),
        ),
        migrations.AddField(
            model_name='image',
            name='url',
            field=models.URLField(null=True),
        ),
    ]
